### ISSUE TITLE
[RFE] Clearly document or warn when a cli argument overrides an environment variable

### ISSUE THREAD

**Issue by akrzos** [kube-burner/kube-burner-ocp#244]
**Is your feature request related to a problem? Please describe.**

I attempted to run a workload configuration file from `kube-burner` with `kube-burner-ocp` and discovered that my environment variables which were consumed by the workload template were still being overridden by the cli arguments default values. For instance I have a workload template resembling:

```yaml
...
  namespacedIterations: true
  podWait: false
  waitWhenFinished: true
  jobPause: {{.JOB_PAUSE_TIME}}
  qps: {{.QPS}}
  burst: {{.BURST}}
  preLoadImages: false
  preLoadPeriod: 1m
...
``` 

Regardless of what I have configured via en environment variable of `QPS` and `BURST`, the default cli arguments take precedence. Maybe there should be a warning that your config file's values for qps/burst will always be sourced from the cli. (Should this exist in default kube-burner since QPS/burst isn't specific to OCP) Alternatively we could formalize what QPS/BURST environment vars would also be read as cli args. I figured I would start the discussion here to improve the experience of a workload moving between kube-burner and kube-burner-ocp.
